//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familymember.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_address> tbl_address { get; set; }
        public virtual DbSet<tbl_events> tbl_events { get; set; }
        public virtual DbSet<tbl_groupadmin> tbl_groupadmin { get; set; }
        public virtual DbSet<tbl_groupuser> tbl_groupuser { get; set; }
        public virtual DbSet<tbl_images> tbl_images { get; set; }
        public virtual DbSet<tbl_member> tbl_member { get; set; }
        public virtual DbSet<tbl_member_role> tbl_member_role { get; set; }
        public virtual DbSet<tbl_notification> tbl_notification { get; set; }
        public virtual DbSet<tbl_relationship> tbl_relationship { get; set; }
        public virtual DbSet<tbl_surname> tbl_surname { get; set; }
        public virtual DbSet<tbl_videos> tbl_videos { get; set; }
        public virtual DbSet<tbl_village> tbl_village { get; set; }
    }
}
