//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familymember.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_surname
    {
        public int Id { get; set; }
        public string SURNAME { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string IS_DELETED { get; set; }
        public Nullable<int> LOGIN_BY { get; set; }
    }
}
