//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familymember.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_groupuser
    {
        public int Id { get; set; }
        public string GROUP_NAME { get; set; }
        public string MEMBER_NAME { get; set; }
        public Nullable<bool> ISADMIN { get; set; }
        public Nullable<System.DateTime> USER_ADDED_DATE { get; set; }
        public Nullable<bool> ISNOTIFY { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public Nullable<int> LOGIN_BY { get; set; }
    }
}
